=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/DeviceConfiguration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="PlateExternalAmp" type="PlateExternalAmp"/>
  <xsd:complexType name="PlateExternalAmp">
    <xsd:sequence>
      <xsd:element name="Physical" type="physical_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sensitivities" type="Sensitivities3_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Control" type="control_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Amplifier" type="amplifier_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Offsets" type="offsets_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="COP_polynomial" type="COP_polynomial_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Crosstalk" type="Crosstalk_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Orientation" type="orientation_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="PlateEthernetAmp" type="PlateEthernetAmp"/>
  <xsd:complexType name="PlateEthernetAmp">
    <xsd:sequence>
      <xsd:element name="Address" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Credentials" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Physical" type="physical_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Control" type="control_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Offsets" type="offsets_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="COP_polynomial" type="COP_polynomial_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Orientation" type="orientation_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="devices_t" type="devices_t"/>
  <xsd:complexType name="devices_t">
    <xsd:sequence minOccurs="0" maxOccurs="1">
      <xsd:element name="ConfigurationName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="EthernetTriggerDevice" type="EthernetTriggerDevice" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Device" type="Device" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="COP_polynomial_t" type="COP_polynomial_t"/>
  <xsd:complexType name="COP_polynomial_t">
    <xsd:sequence>
      <xsd:element name="X" type="xsd:float" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="Y" type="xsd:float" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="physical_t" type="physical_t"/>
  <xsd:complexType name="physical_t">
    <xsd:sequence minOccurs="1" maxOccurs="1">
      <xsd:element name="Width_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Length_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="a_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="b_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Azx_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Azy_mm" type="xsd:float" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="offsets_t" type="offsets_t"/>
  <xsd:complexType name="offsets_t">
    <xsd:annotation>
      <xsd:documentation>Offsets for channels</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="AutoAdjustOffsets" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Offset_mV" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="Sensitivities3_t" type="Sensitivities3_t"/>
  <xsd:complexType name="Sensitivities3_t">
    <xsd:sequence>
      <xsd:element name="Sx_pCperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sy_pCperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sz_pCperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="PlateStrainGage" type="PlateStrainGage"/>
  <xsd:complexType name="PlateStrainGage">
    <xsd:sequence>
      <xsd:element name="Physical" type="physical_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Matrix" type="SensitivityMatrix6x6_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Offsets" type="offsets_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="AmplifierGain" type="AmplifierGain_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Orientation" type="orientation_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="SensitivitiesAux_t" type="SensitivitiesAux_t"/>
  <xsd:complexType name="SensitivitiesAux_t">
    <xsd:sequence>
      <xsd:element name="S_mVperMU" type="xsd:float" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="Devices" type="devices_t"/>
  <xsd:element name="Crosstalk_t" type="Crosstalk_t"/>
  <xsd:complexType name="Crosstalk_t">
    <xsd:sequence>
      <xsd:element name="FxtoFy" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="FxtoFz" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="FytoFx" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="FytoFz" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="FztoFx" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="FztoFy" type="xsd:float" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="Auxiliary" type="Auxiliary"/>
  <xsd:complexType name="Auxiliary">
    <xsd:sequence>
      <xsd:element name="Sensitivities" type="SensitivitiesAux_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Offsets" type="offsets_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="Sensitivities8_t" type="Sensitivities8_t"/>
  <xsd:complexType name="Sensitivities8_t">
    <xsd:sequence>
      <xsd:element name="Sx12_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sx34_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sy14_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sy23_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sz1_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sz2_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sz3_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sz4_mVperN" type="xsd:float" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="SensitivityMatrix6x6_t" type="SensitivityMatrix6x6_t"/>
  <xsd:complexType name="SensitivityMatrix6x6_t">
    <xsd:sequence>
      <xsd:element name="R1_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="R2_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="R3_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="R4_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="R5_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="R6_S" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:simpleType name="RangeEnum">
    <xsd:annotation>
      <xsd:documentation>Specify the amplifier range</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Range1"/>
      <xsd:enumeration value="Range2"/>
      <xsd:enumeration value="Range3"/>
      <xsd:enumeration value="Range4"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="control_t" type="control_t"/>
  <xsd:complexType name="control_t">
    <xsd:sequence>
      <xsd:element name="RangeXY" type="RangeEnum" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="RangeZ" type="RangeEnum" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="UseTimeConstant" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="amplifier_t" type="amplifier_t"/>
  <xsd:complexType name="amplifier_t">
    <xsd:sequence>
      <xsd:element name="RangeXY_pC" type="xsd:float" minOccurs="1" maxOccurs="1">
        <xsd:annotation>
          <xsd:documentation>FSO Range in pC</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RangeZ_pC" type="xsd:float" minOccurs="1" maxOccurs="1">
        <xsd:annotation>
          <xsd:documentation>FSO Range in pC</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="FSO_mV" type="xsd:float" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="Device" type="Device"/>
  <xsd:complexType name="Device">
    <xsd:sequence>
      <xsd:element name="StartChannel" type="xsd:int" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Channels" type="xsd:int" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Type" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="SerialNumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Manufacturer" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Name" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Units" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
      <xsd:choice minOccurs="1" maxOccurs="1">
        <xsd:element name="PlateInternalAmp" type="PlateInternalAmp" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="PlateExternalAmp" type="PlateExternalAmp" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Auxiliary" type="Auxiliary" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="PlateStrainGage" type="PlateStrainGage" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="VirtualPlate" type="VirtualPlate" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="PlateEthernetAmp" type="PlateEthernetAmp" minOccurs="1" maxOccurs="1"/>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="EthernetTriggerDevice" type="EthernetTriggerDevice"/>
  <xsd:complexType name="EthernetTriggerDevice">
    <xsd:sequence>
      <xsd:element name="Type" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="SerialNumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Manufacturer" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Name" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Address" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Credentials" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Custom" type="Custom" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="PlateInternalAmp" type="PlateInternalAmp"/>
  <xsd:complexType name="PlateInternalAmp">
    <xsd:sequence>
      <xsd:element name="Physical" type="physical_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Sensitivities" type="Sensitivities8_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Control" type="control_t" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Offsets" type="offsets_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="COP_polynomial" type="COP_polynomial_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Crosstalk" type="Crosstalk_t" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Orientation" type="orientation_t" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="AmplifierGain_t" type="AmplifierGain_t"/>
  <xsd:complexType name="AmplifierGain_t">
    <xsd:sequence>
      <xsd:element name="Gain" type="xsd:float" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="orientation_t" type="orientation_t"/>
  <xsd:complexType name="orientation_t">
    <xsd:sequence>
      <xsd:element name="dx_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="dy_mm" type="xsd:float" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="alpha_deg" type="xsd:float" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="VirtualPlate" type="VirtualPlate"/>
  <xsd:complexType name="VirtualPlate">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="Custom">
    <xsd:sequence>
      <xsd:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/sample_external.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xsi:noNamespaceSchemaLocation="DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <ConfigurationName>Configuration 1</ConfigurationName>
  <Device>
    <StartChannel>1</StartChannel>
    <Channels>8</Channels>
    <Type>9281B11</Type>
    <SerialNumber>216137</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate 1</Name>
    <PlateExternalAmp>
      <Physical>
        <Width_mm>400</Width_mm>
        <Length_mm>600</Length_mm>
        <a_mm>120</a_mm>
        <b_mm>200</b_mm>
        <Azx_mm>-163</Azx_mm>
      </Physical>
      <Sensitivities>
        <Sx_pCperN>-7.78</Sx_pCperN>
        <Sy_pCperN>-7.79</Sy_pCperN>
        <Sz_pCperN>-3.85</Sz_pCperN>
      </Sensitivities>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
        <UseTimeConstant>false</UseTimeConstant>
      </Control>
      <Amplifier>
        <RangeXY_pC>5000</RangeXY_pC>
        <RangeZ_pC>10000</RangeZ_pC>
        <FSO_mV>10000</FSO_mV>
      </Amplifier>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
        <Offset_mV>5</Offset_mV>
        <Offset_mV>5</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
      </Offsets>
      <COP_polynomial>
        <X>2.51997e-015</X>
        <X>-2.18826e-010</X>
        <X>-2.69254e-007</X>
        <X>-4.85912e-011</X>
        <X>4.55731e-006</X>
        <X>-0.0418892</X>
        <Y>2.8375e-015</Y>
        <Y>-1.00051e-010</Y>
        <Y>-2.05349e-006</Y>
        <Y>-1.16374e-010</Y>
        <Y>4.71553e-006</Y>
        <Y>0.0689265</Y>
      </COP_polynomial>
      <Orientation>
        <dx_mm>200</dx_mm>
        <dy_mm>400</dy_mm>
        <alpha_deg>315</alpha_deg>
      </Orientation>
    </PlateExternalAmp>
  </Device>
  
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/sample_ethernet.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xsi:noNamespaceSchemaLocation="DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ConfigurationName>Ethernet Sample Configuration</ConfigurationName>
  <EthernetTriggerDevice>
    <Type>5167A</Type>
    <SerialNumber>5544495</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>LabAmp-5544495</Name>
    <Address>192.168.123.203</Address>  
  </EthernetTriggerDevice>
  <Device>
    <Type>9287CBQ02</Type>
    <SerialNumber>5582391</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate-5582391</Name>
    <PlateEthernetAmp>
      <Address>Plate-5582391</Address>  
      <!-- <Address>192.168.100.101</Address> optional by IPv4 address -->
      <Physical>
        <Width_mm>600</Width_mm>
        <Length_mm>900</Length_mm>
        <a_mm>210</a_mm>
        <b_mm>350</b_mm>
        <Azx_mm>-652</Azx_mm>
      </Physical>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
        <UseTimeConstant>false</UseTimeConstant>
      </Control>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
      </Offsets>
    </PlateEthernetAmp>
  </Device>
  <Device>
    <Type>9287CBQ02</Type>
    <SerialNumber>5582392</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate-5582392</Name>
    <PlateEthernetAmp>
      <Address>192.168.100.102</Address>  
      <!-- <Address>Plate-5582392</Address> optional by name -->
      <Physical>
        <Width_mm>600</Width_mm>
        <Length_mm>900</Length_mm>
        <a_mm>210</a_mm>
        <b_mm>350</b_mm>
        <Azx_mm>-652</Azx_mm>
      </Physical>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
        <UseTimeConstant>false</UseTimeConstant>
      </Control>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
      </Offsets>
    </PlateEthernetAmp>
  </Device>
  <Device>
    <Type>9287CBQ02</Type>
    <SerialNumber>5582395</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate-5582395</Name>
    <PlateEthernetAmp>
      <Address>192.168.100.103</Address> 
      <!-- <Address>Plate-5582395</Address> optional by name -->      
      <Physical>
        <Width_mm>600</Width_mm>
        <Length_mm>900</Length_mm>
        <a_mm>210</a_mm>
        <b_mm>350</b_mm>
        <Azx_mm>-652</Azx_mm>
      </Physical>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
        <UseTimeConstant>false</UseTimeConstant>
      </Control>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
      </Offsets>
    </PlateEthernetAmp>
  </Device>
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/Python/ConfigUSB.xml
<?xml version="1.0" encoding="utf-8" ?>
<Devices xsi:noNamespaceSchemaLocation="C:\Program Files (x86)\Kistler\DataServer\DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ConfigurationName>Config 1</ConfigurationName>
    <Device>
        <StartChannel>1</StartChannel>
        <Channels>8</Channels>
        <Type>9281CA (SN&gt;616901)</Type>
        <SerialNumber></SerialNumber>
        <Name>Plate 1</Name>
        <PlateInternalAmp>
            <Physical>
                <Width_mm>400</Width_mm>
                <Length_mm>600</Length_mm>
                <a_mm>120</a_mm>
                <b_mm>200</b_mm>
                <Azx_mm>-45</Azx_mm>
            </Physical>
            <Sensitivities>
                <Sx12_mVperN>4</Sx12_mVperN>
                <Sx34_mVperN>4</Sx34_mVperN>
                <Sy14_mVperN>4</Sy14_mVperN>
                <Sy23_mVperN>4</Sy23_mVperN>
                <Sz1_mVperN>1</Sz1_mVperN>
                <Sz2_mVperN>1</Sz2_mVperN>
                <Sz3_mVperN>1</Sz3_mVperN>
                <Sz4_mVperN>1</Sz4_mVperN>
            </Sensitivities>
            <Control>
                <RangeXY>Range3</RangeXY>
                <RangeZ>Range4</RangeZ>
            </Control>
            <Offsets>
                <AutoAdjustOffsets>true</AutoAdjustOffsets>
            </Offsets>
            <COP_polynomial>
                <X>7.92063e-015</X>
                <X>-5.821e-010</X>
                <X>-2.77102e-006</X>
                <X>-1.76083e-010</X>
                <X>1.29695e-005</X>
                <X>-0.0413979</X>
                <Y>8.82869e-015</Y>
                <Y>-2.48554e-010</Y>
                <Y>-1.76282e-006</Y>
                <Y>-4.22186e-010</Y>
                <Y>1.2091e-005</Y>
                <Y>0.0516279</Y>
            </COP_polynomial>
            <Orientation>
                <dx_mm>0</dx_mm>
                <dy_mm>0</dy_mm>
                <alpha_deg>0</alpha_deg>
            </Orientation>
        </PlateInternalAmp>
    </Device>
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/sample_multi.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xsi:noNamespaceSchemaLocation="DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <ConfigurationName>Configuration 3</ConfigurationName>
  <Device>
    <StartChannel>1</StartChannel>
    <Channels>8</Channels>
    <Type>9281CA</Type>
    <SerialNumber>591279</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate 1</Name>
    <PlateInternalAmp>
      <Physical>
        <Width_mm>400</Width_mm>
        <Length_mm>600</Length_mm>
        <a_mm>120</a_mm>
        <b_mm>200</b_mm>
        <Azx_mm>-45</Azx_mm>
      </Physical>
      <Sensitivities>
        <Sx12_mVperN>19.989</Sx12_mVperN>
        <Sx34_mVperN>19.711</Sx34_mVperN>
        <Sy14_mVperN>20.119</Sy14_mVperN>
        <Sy23_mVperN>20.161</Sy23_mVperN>
        <Sz1_mVperN>2.916</Sz1_mVperN>
        <Sz2_mVperN>2.903</Sz2_mVperN>
        <Sz3_mVperN>2.971</Sz3_mVperN>
        <Sz4_mVperN>2.944</Sz4_mVperN>
      </Sensitivities>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
      </Control>
      <Offsets>
        <AutoAdjustOffsets>true</AutoAdjustOffsets>
      </Offsets>
     </PlateInternalAmp>
  </Device>

  <Device>
    <StartChannel>9</StartChannel>
    <Channels>6</Channels>
    <Type>SG1</Type>
    <SerialNumber>12345</SerialNumber>
    <Manufacturer>MFG-A</Manufacturer>
    <Name>Plate 2</Name>
      <PlateStrainGage>
        <Physical>
          <Width_mm>400</Width_mm>
          <Length_mm>600</Length_mm>
          <a_mm>10</a_mm>
          <b_mm>20</b_mm>
          <Azx_mm>30</Azx_mm>
        </Physical>
        <Matrix>
          <R1_S>1000</R1_S>
          <R1_S>0</R1_S>
          <R1_S>0</R1_S>
          <R1_S>0</R1_S>
          <R1_S>0</R1_S>
          <R1_S>0</R1_S>
          <R2_S>0</R2_S>
          <R2_S>1000</R2_S>
          <R2_S>0</R2_S>
          <R2_S>0</R2_S>
          <R2_S>0</R2_S>
          <R2_S>0</R2_S>
          <R3_S>0</R3_S>
          <R3_S>0</R3_S>
          <R3_S>1000</R3_S>
          <R3_S>0</R3_S>
          <R3_S>0</R3_S>
          <R3_S>0</R3_S>
          <R4_S>0</R4_S>
          <R4_S>0</R4_S>
          <R4_S>0</R4_S>
          <R4_S>1000</R4_S>
          <R4_S>0</R4_S>
          <R4_S>0</R4_S>
          <R5_S>0</R5_S>
          <R5_S>0</R5_S>
          <R5_S>0</R5_S>
          <R5_S>0</R5_S>
          <R5_S>1000</R5_S>
          <R5_S>0</R5_S>
          <R6_S>0</R6_S>
          <R6_S>0</R6_S>
          <R6_S>0</R6_S>
          <R6_S>0</R6_S>
          <R6_S>0</R6_S>
          <R6_S>1000</R6_S>
        </Matrix>
        <Offsets>
          <AutoAdjustOffsets>true</AutoAdjustOffsets>
          <Offset_mV>0</Offset_mV>
        </Offsets>
        <AmplifierGain>
          <Gain>10</Gain>
          <Gain>10</Gain>
          <Gain>10</Gain>
          <Gain>5</Gain>
          <Gain>5</Gain>
          <Gain>5</Gain>
        </AmplifierGain>
      </PlateStrainGage>
  </Device>
  
  <Device>
    <StartChannel>15</StartChannel>
    <Channels>1</Channels>
    <Type>Accelerometer</Type>
    <SerialNumber>K12345</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Accelerometer 1</Name>
    <Units>m/s/s</Units>
    <Auxiliary>
      <Sensitivities>
        <S_mVperMU>1000</S_mVperMU>
      </Sensitivities>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
        <Offset_mV>5000</Offset_mV>
      </Offsets>
    </Auxiliary>
  </Device>
  
  <Device>
    <StartChannel>16</StartChannel>
    <Channels>1</Channels>
    <Type>Accelerometer</Type>
    <SerialNumber>K12346</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Accelerometer 2</Name>
    <Units>m/s/s</Units>
    <Auxiliary>
      <Sensitivities>
        <S_mVperMU>1002.5</S_mVperMU>
      </Sensitivities>
      <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
        <Offset_mV>5000</Offset_mV>
      </Offsets>
    </Auxiliary>
  </Device>
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/Python/Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<Devices xsi:noNamespaceSchemaLocation="C:\Program Files (x86)\Kistler\DataServer\DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ConfigurationName>Config 1</ConfigurationName>
    <Device>
        <Type>5167A81</Type>
        <SerialNumber>5536327</SerialNumber>
        <Name>LabAmp-5536327</Name>
        <PlateEthernetAmp>
            <Address>192.168.123.217</Address>
            <Physical>
                <Width_mm>900</Width_mm>
                <Length_mm>900</Length_mm>
                <a_mm>350</a_mm>
                <b_mm>350</b_mm>
                <Azx_mm>-70</Azx_mm>
            </Physical>
            <Control>
                <RangeXY>Range3</RangeXY>
                <RangeZ>Range4</RangeZ>
            </Control>
            <Offsets>
                <AutoAdjustOffsets>false</AutoAdjustOffsets>
            </Offsets>
            <COP_polynomial>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <X>0</X>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
                <Y>0</Y>
            </COP_polynomial>
            <Orientation>
                <dx_mm>0</dx_mm>
                <dy_mm>0</dy_mm>
                <alpha_deg>0</alpha_deg>
            </Orientation>
           <MoCapData>
              <Location>
                 <dx_mm>200</dx_mm>
                 <dy_mm>300</dy_mm>
                 <dz_mm>0</dz_mm>
              </Location>
              <Orientation>
                 <rx_deg>0</rx_deg>
                 <ry_deg>0</ry_deg>
                 <rz_deg>0</rz_deg>
             </Orientation>
	       </MoCapData>
           <Custom>
              <Message></Message>
           </Custom>            
        </PlateEthernetAmp>
    </Device>
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xsi:noNamespaceSchemaLocation="DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ConfigurationName>Configuration 1</ConfigurationName>
  <Device>
    <StartChannel>1</StartChannel>
    <Channels>8</Channels>
    <Type>9281CA</Type>
    <SerialNumber>1645220</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate 1</Name>
    <PlateInternalAmp>
      <Physical>
        <Width_mm>400</Width_mm>
        <Length_mm>600</Length_mm>
        <a_mm>120</a_mm>
        <b_mm>200</b_mm>
        <Azx_mm>-63</Azx_mm>
      </Physical>
      <Sensitivities>
        <Sx12_mVperN>1000</Sx12_mVperN>
        <Sx34_mVperN>1000</Sx34_mVperN>
        <Sy14_mVperN>1000</Sy14_mVperN>
        <Sy23_mVperN>1000</Sy23_mVperN>
        <Sz1_mVperN>1000</Sz1_mVperN>
        <Sz2_mVperN>1000</Sz2_mVperN>
        <Sz3_mVperN>1000</Sz3_mVperN>
        <Sz4_mVperN>1000</Sz4_mVperN>
      </Sensitivities>
      <Control>
        <RangeXY>Range1</RangeXY>
        <RangeZ>Range2</RangeZ>
      </Control>
       <Offsets>
        <AutoAdjustOffsets>false</AutoAdjustOffsets>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
        <Offset_mV>0</Offset_mV>
      </Offsets>
    </PlateInternalAmp>
  </Device>
</Devices>

=== Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience/Samples/XML/sample_internal.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xsi:noNamespaceSchemaLocation="DeviceConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <ConfigurationName>Configuration 1</ConfigurationName>
  <Device>
    <StartChannel>1</StartChannel>
    <Channels>8</Channels>
    <Type>9281CA</Type>
    <SerialNumber>591279</SerialNumber>
    <Manufacturer>Kistler</Manufacturer>
    <Name>Plate 1</Name>
    <PlateInternalAmp>
      <Physical>
        <Width_mm>400</Width_mm>
        <Length_mm>600</Length_mm>
        <a_mm>120</a_mm>
        <b_mm>200</b_mm>
        <Azx_mm>-45</Azx_mm>
      </Physical>
      <Sensitivities>
        <Sx12_mVperN>19.989</Sx12_mVperN>
        <Sx34_mVperN>19.711</Sx34_mVperN>
        <Sy14_mVperN>20.119</Sy14_mVperN>
        <Sy23_mVperN>20.161</Sy23_mVperN>
        <Sz1_mVperN>2.916</Sz1_mVperN>
        <Sz2_mVperN>2.903</Sz2_mVperN>
        <Sz3_mVperN>2.971</Sz3_mVperN>
        <Sz4_mVperN>2.944</Sz4_mVperN>
      </Sensitivities>
      <Control>
        <RangeXY>Range2</RangeXY>
        <RangeZ>Range3</RangeZ>
      </Control>
      <Offsets>
        <AutoAdjustOffsets>true</AutoAdjustOffsets>
      </Offsets>
     </PlateInternalAmp>
  </Device>
  
</Devices>
